catalogo/jogos/urls.py
from django.urls import path
from jogos.views import *

urlpatterns = [
    path('', index, name='index'),
    path('login', login, name='login'),
    path('cadastro', register, name='cadastro'),
    path('logout', logout, name='logout'),
    path('dashboard/users', index, name="users"),
    path('inativar/<int:id>', inative, name="inative_user"),
    path('ativar/<int:id>', active, name="active_user"),
    path('dashboard', dashboard, name="dashboard"),
    path('add_jogos', add_jogos, name="add_jogos"),
    path('consulta_jogos', consulta_jogos, name='consulta_jogos'),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
]

catalogo/setup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jogos.urls')),
    path('usuarios/', include('usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/usuarios/urls.py
from django.urls import path
from usuarios.views import *

urlpatterns = [
    path('', login, name='login'),
    path('cadastro', register, name='cadastro'),
    path('logout', logout, name='logout'),
    path('dashboard/users', index, name="users"),
    path('inativar/<int:id>', inative, name="inative_user"),
    path('ativar/<int:id>', active, name="active_user"),
    path('dashboard', dashboard, name="dashboard"),
    path('add_jogos', add_jogos, name="add_jogos"),
    path('consulta_jogos', consulta_jogos, name='consulta_jogos'),
    path('edit/<int:id>', edit, name="edit"),
    path('update/<int:id>', update, name="update"),
    path('delete/<int:id>', delete, name="delete"),
]

catalogo/jogos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Jogo(models.Model):
    nome = models.CharField(max_length=20)
    imagem = models.ImageField(upload_to='media/')
    descricao = models.TextField(max_length=50)

    def __str__(self):
        return self.nome

catalogo/usuarios/models.py
from django.db import models

# Create your models here.

catalogo/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class LoginForms(forms.Form):
    email = forms.EmailField(
        label='Email',
        required=True,
        max_length=100,
        widget=forms.EmailInput(
            attrs={
                'type': "email",
            }
        )
    )
    senha = forms.CharField(
        label='Senha',
        required=True,
        max_length=70,
        widget=forms.PasswordInput(
            attrs={
                'type': 'password',
            }
        ),
    )


class UserForms(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'custom-input'})),
    password_confirm = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'custom-input'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'custom-input'}),
            'email': forms.TextInput(attrs={'class': 'custom-input'}),
            'password': forms.PasswordInput(attrs={'class': 'custom-input'}),
        }

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Senhas não são iguais')

        return password_confirm

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        user.is_staff = 1
        if commit:
            user.save()
        return user

class RegisterForms(forms.Form):
    email = forms.EmailField(
        label='Email',
        required=True,
        max_length=100,
        widget=forms.EmailInput(attrs={'type': 'email'}),
    )
    username = forms.CharField(
        label='Username',
        required=True,
        max_length=30,
        widget=forms.TextInput(attrs={'type': 'text'}),
    )
    password = forms.CharField(
        label='Senha',
        required=True,
        max_length=100,
        widget=forms.PasswordInput(attrs={'type': 'password'}),
    )
    password_confirm = forms.CharField(
        label='Confirmar Senha',
        required=True,
        max_length=100,
        widget=forms.PasswordInput(attrs={'type': 'password'}),
    )


    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Senhas não são iguais')

        return password_confirm

catalogo/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from jogos.models import Jogo
from jogos.forms import JogoForm
from django.core.paginator import Paginator, EmptyPage
from usuarios.forms import LoginForms, RegisterForms
from django.db.models import Q

@login_required
def index(request):
    user = User.objects.all()
    register_form = RegisterForms()
    login_form = LoginForms()
    # Criar uma instância do formulário JogoForm
    jogo_form = JogoForm()

    # Obter todos os produtos
    produtos = Jogo.objects.all()

    # Filtrar por termo de pesquisa, se fornecido
    search_term = request.GET.get('search', '')
    
    if search_term:
        produtos = Jogo.objects.filter(nome__icontains=search_term)
    else:
        produtos = Jogo.objects.all()

    # Número de itens por página
    items_por_pagina = 8

    # Obter o número da página a partir dos parâmetros da solicitação
    page = request.GET.get('page', 1)

    # Criar um objeto Paginator
    paginator = Paginator(produtos, items_por_pagina)

    try:
        produtos_paginados = paginator.page(page)
    except EmptyPage:
        # Se a página solicitada estiver fora do intervalo, exibir a última página disponível
        produtos_paginados = paginator.page(paginator.num_pages)

    return render(request, 'jogos/index.html', {'users': user, 'register_form': register_form, 'user_form': login_form, 'form': jogo_form, 'produtos_paginados': produtos_paginados, 'search_term': search_term})

@login_required
def dashboard(request):
    produtos = Jogo.objects.all()
    return render(request, "dashboard/dashboard.html", {'produtos': produtos })

@login_required
def add_jogos(request):
    if request.method == 'POST':
        form = JogoForm(request.POST, request.FILES)
        if form.is_valid():
            jogo = form.save(commit=False)
            jogo.save()
            return redirect('add_jogos')
    else:
        form = JogoForm()

    return render(request, 'usuarios/login.html', {'form': JogoForm})

@login_required
def listarJogos(request):
    search_query = request.GET.get('search')
    if search_query:
        produtos = Jogo.objects.filter(Q(titulo__icontains=search_query) | Q(autor__username__icontains=search_query))
    else:
        produtos = Jogo.objects.all()
    return render(request,"usuarios/users.html",{"produtos":produtos})

@login_required
def consulta_jogos(request):
    produtos = Jogo.objects.all()
    return render(request, 'usuarios/users.html', {'produtos':produtos})

@login_required
def edit(request, id):
    produtos = Jogo.objects.get(pk=id)
    return render(request, "usuarios/create_user.html",{'produtos':produtos})

@login_required
def update(request, id):
    produtos = Jogo.objects.get(pk=id)
    produtos.nome = request.POST['nome']
    produtos.descricao = request.POST['descricao']
    produtos.imagem = request.FILES['imagem']
    produtos.save()
    return redirect('listarJogos')

@login_required
def delete(request, id):
    produtos = Jogo.objects.get(pk=id)
    produtos.delete()
    return redirect('consulta_jogos')


def login(request):  # Renomeie esta função
    user_form = LoginForms()
    produtos = Jogo.objects.all()
    # Criar uma instância do formulário JogoForm
    jogo_form = JogoForm()
    
    # Se houver um termo de pesquisa na solicitação GET
    search_term = request.GET.get('search', '')
    
    if search_term:
        produtos = Jogo.objects.filter(nome__icontains=search_term)
    else:
        produtos = Jogo.objects.all()
    
    # Se houver um termo de pesquisa, filtra os produtos
    if search_term:
        produtos = Jogo.objects.filter(nome__icontains=search_term)
    else:
        produtos = Jogo.objects.all()

    # Número de itens por página
    items_por_pagina = 8  # Altere conforme necessário

    # Obtém o número da página a partir dos parâmetros da solicitação
    page = request.GET.get('page', 1)

    # Cria um objeto Paginator
    paginator = Paginator(produtos, items_por_pagina)

    try:
        produtos_paginados = paginator.page(page)
    except EmptyPage:
        # Se a página solicitada estiver fora do intervalo, exibe a última página disponível
        produtos_paginados = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        user_form = LoginForms(request.POST)

    if user_form.is_valid():
        email = user_form['email'].value()
        senha = user_form['senha'].value()
        user_temp = User.objects.get(email=email)

        usuario = auth.authenticate(
            request,
            username=user_temp.username,
            password=senha
        )

        if usuario is not None:
            auth.login(request, usuario)
            messages.success(request, 'Foi logado com sucesso!')
            if usuario.is_staff:
                return redirect('dashboard')
            else:
                return redirect('index')
        else:
            messages.error(request, 'Erro ao efetuar login')
            return redirect('index')

    return render(request, 'jogos/index.html', {'user_form': user_form, 'produtos':produtos_paginados, 'form': jogo_form, 'search_term': search_term})


@login_required
def register(request):
    if request.method == 'POST':
        form = RegisterForms(request.POST)

        if form.is_valid():
            name = form['name'].value()
            email = form['email'].value()
            password = form['password'].value()

            if User.objects.filter(username=name).exists():
                messages.error(request, 'Usuário já existente')
                return redirect('users')

            usuario = User.objects.create_user(
                username=name,
                email=email,
                password=password
            )
            usuario.save()
            messages.success(request, 'Usuario cadastrado com sucesso!')
            return redirect('users')

@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, 'Logout efetuado com sucesso!')
    return redirect('login')

@login_required
def inative(request, id):
    user = User.objects.get(id=id)
    user.is_active = False
    user.save()
    messages.success(request, 'Usuario inativado com sucesso!')
    return redirect('users')

@login_required
def active(request, id):
    user = User.objects.get(id=id)
    user.is_active = True
    user.save()
    messages.success(request, 'Usuario ativado com sucesso!')
    return redirect('users')

catalogo/templates/usuarios/create_user.html
{% extends "dashboard/layouts/layout.html" %}
{% load static %}
{% block content %}
<div class="main">
  <form method="POST" action="{% url 'update' produtos.id %}" enctype="multipart/form-data" class="custom-form">
      {% csrf_token %}
      <div class="form-group">
          <label for="id_titulo">Nome:</label>
          <input type="text" name="titulo" class="custom-input" maxlength="25" required="" id="id_nome" value="{{jogo.nome}}">
      </div>
      <div class="form-group">
          <label for="id_descricao">Descricao:</label>
          <textarea name="descricao" cols="40" rows="10" class="custom-textarea" maxlength="255" required="" id="id_descricao" value="{{jogo.descricao}}"></textarea>
      </div>
      <div class="form-group">
          <label for="id_foto">Imagem:</label>
          <input type="file" name="foto" class="custom-file-input" accept="media/*" required="" id="id_foto" value="{{jogo.imagem}}">
      </div>
      <button type="submit" class="custom-button">Editar Jogo</button>
  </form>
</div>
{% endblock %}

catalogo/templates/usuarios/login.html
{% extends "dashboard/layouts/layout.html" %}
{% load static %}
{% block content %}

<div class="main">
  <form method="post" enctype="multipart/form-data" class="custom-form">
    {% csrf_token %}

    <div class="form-group">
      <label for="{{ form.nome.id_for_label }}" class="form-label">{{ form.nome.label }}</label>
      {{ form.nome }}
    </div>

    <div class="form-group">
      <label for="{{ form.descricao.id_for_label }}" class="form-label">{{ form.descricao.label }}</label>
      {{ form.descricao }}
    </div>

    <div class="form-group">
      <label for="{{ form.imagem.id_for_label }}" class="form-label">{{ form.imagem.label }}</label>
      {{ form.imagem }}
    </div>

    <button type="submit" class="custom-button">Adicionar Jogo</button>
  </form>
</div>

{% endblock %}

catalogo/templates/usuarios/users.html
{% extends "dashboard/layouts/layout.html" %}
{% load static %}
{% block content %}
<div class="main">
    <div class="photo-list">
        <h2>Jogos adicionados:</h2>
        <div class="card-container" style="display: flex; flex-wrap: wrap; gap: 20px;">
            {% for jogo in produtos %}
                <div class="card" style="flex: 1 1 calc(30% - 20px); max-width: calc(30% - 20px); min-width: calc(30% - 20px);">
                    <div style="position: relative; overflow: hidden; border-radius: 0.25rem; margin-bottom: 1.5rem;">
                        <img src="{{ jogo.imagem.url }}" style="width: 100%; height: 200px; object-fit: cover; border-top-left-radius: 0.25rem; border-top-right-radius: 0.25rem;" alt="{{ jogo.titulo }}">
                        <div style="padding: 1rem;">
                            <h5 style="margin-bottom: 0.5rem;">{{ jogo.nome }}</h5>
                            <p style="margin-top: 0; margin-bottom: 1rem;">Descrição: {{ jogo.descricao }}</p>
                            <hr>
                            <div style="text-decoration: none;">
                                <a href="{% url 'edit' jogo.id %}">
                                   <svg xmlns="http://www.w3.org/2000/svg" style="background-color: orange; border-radius:5px;" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"></path><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"></path></svg>
                               </a>
                               <a href="{% url 'delete' jogo.id %}">
                                   <svg xmlns="http://www.w3.org/2000/svg" style="background-color: red; border-radius:5px;" width="30" height="30" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-trash-2"><polyline points="3 6 5 6 21 6"></polyline><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"></path><line x1="10" y1="11" x2="10" y2="17"></line><line x1="14" y1="11" x2="14" y2="17"></line></svg>
                               </a>
                           </div>
                            
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}